Add READMES to quark script showcases
quark-engine/quark-script pull request #1
Opened 2022-12-05 12:27 UTC by zinwang

# Description

This PR aims to update Quark Script to the repo and complete the README file of each Quark Script showcase.

# File Changes
 + Add CWE-327 Quark Script 
 + Add a README file to each showcase

2022-12-06 06:45 UTC, haeter525 commented on CWE-94/README.md
> +## Quark Scipt: CWE-94.py
Please correct the spelling here.

2022-12-06 06:48 UTC, haeter525 commented on CWE-312/README.md
> +First, we designed a Frida script agent.js to hook the target method and get the arguments when the target method is called. Then we hook the method putString to catch its arguments. Finally, we use
The links to the official websites of Frida and Ciphey is missing. Please correct it.

2022-12-06 07:18 UTC, haeter525 requested changes
Hi @zinwang. Thanks for the patch.
I've left one comment on the changes.

Also, I found some content is formatted differently from the document.
1. the APIs and the file name are not marked with backticks.
2. some words are not in bold.

Please fix them as well. Thanks.

2022-12-06 08:04 UTC, zinwang commented
@haeter525 
I fixed grammar flaws in CWE-94 and added links to CWE-312.
Also, the formats in all the CWEs are the same as the document.
Please have a look! Thank you!

2022-12-07 01:31 UTC, haeter525 approved these changes
Thank @zinwang. LGTM!

2022-12-07 01:32 UTC, merged