Introducing new team member Quark Script Agent
quark-engine/quark-script pull request #37
Opened 2024-07-26 07:44 UTC by pulorsok

# Quark Script Agent

Quark Script Agent is designed to help users easily utilize the Quark Script API to analyze their desired targets.

Quark Script Agent allows users to seamlessly add custom analysis features to the Quark Script API.

Quark Script Agent integrates with LangChain, connecting large language models with the Quark Script API. This integration enables users to perform analyses using natural language commands. By leveraging the power of LangChain and large language models, Quark Script Agent simplifies the process of interacting with the Quark Script API, making it accessible even to those who may not be familiar with programming or scripting.

## Use case of Quark Script CWE-798

> Since LangChain currently does not support passing Python instances between tools, we are temporarily using global variables to pass parameters between tools in quarkScriptAgent.py.

Quark Script CWE-798 analysis process:

1. Use the Quark Script API `Rule()` to define behavior.
2. Use the Quark Script API `runQuarkAnalysis()` to locate the  behavior.
4. Use the Quark Script API `getParameterValues()` to retrieve parameter values.
5. Use the Quark Script API `isHardCoded()` to check if a parameter is hard-coded.

The `Rule()`, `runQuarkAnalysis()`, `getParameterValues()`, and `isHardCoded()` functions are treated as **tools** within LangChain, enabling them to be invoked through the `gpt-4o` model to analyze and identify [CWE-798](https://cwe.mitre.org/data/definitions/798.html) vulnerabilities in the [ovaa.apk](https://github.com/oversecured/ovaa) sample.

#### Architecture

<img width="829" alt="截圖 2024-07-26 下午3 40 32" src="https://github.com/user-attachments/assets/f17bfba0-43d7-4236-9775-bb0d3b961907">

#### Prompt
> Initialize rule instance with the rule path set to "rule.json"

> Run Quark Analysis using the rule instance on the apk sample "ovaa.apk", and Check if the parameters are hard-coded. If yes, display the hard-coded values.

#### Result

<img width="1440" alt="截圖 2024-07-26 下午3 39 12" src="https://github.com/user-attachments/assets/9c8ba9d3-c8b5-4583-8cb8-750f8c3bf2a7">

#### rule.json

```json=
{
    "crime": "Detect APK using SecretKeySpec.",
    "permission": [],
    "api": [
        {
            "descriptor": "()[B",
            "class": "Ljava/lang/String;",
            "method": "getBytes"
        },
        {
            "descriptor": "([BLjava/lang/String;)V",
            "class": "Ljavax/crypto/spec/SecretKeySpec;",
            "method": "<init>"
        }
    ],
    "score": 1,
    "label": []
}
```

2024-07-26 13:19 UTC, 18z commented
# Quark Script Agent

Introducing Quark's new member, the Quark Script Agent, the first AI assistant in the Quark team. This agent enables users to perform analyses using natural language, without the need for programming or scripting expertise, making the process simple and user-friendly.

The Quark Script Agent integrates with LangChain, which utilizes OpenAI's large language models to act as a bridge between natural language and the Quark Script API. LangChain defines the Quark Script API as a tool that large language models can understand and use. This means that users can easily call new analysis APIs using natural language commands by simply adding new tools as needed.

## Showcase: Detecting CWE-798 with Quark Script Agent
Here's an example of using the Quark Script Agent with the `quarkScriptAgent.py`. This agent can currently detect [CWE-798](https://cwe.mitre.org/data/definitions/798.html) vulnerability in the [ovaa.apk](https://github.com/oversecured/ovaa). See the details below.

### Installation

To install the Quark Script Agent, you need to install the following dependencies:

1. clone the repository:
```
git clone https://github.com/quark-engine/quark-script.git
```

2. Install the required packages:
```
pip install -r requirements.txt
```

3. Run the script:
```
python quarkScriptAgent.py
```

### Result

<img width="1440" alt="截圖 2024-07-26 下午3 39 12" src="https://github.com/user-attachments/assets/9c8ba9d3-c8b5-4583-8cb8-750f8c3bf2a7">

### Decode the Prompts
Here are two prompts, each for executing different analysis processes.

```
1st Prompt: Initialize the rule instance with the rule path set to "rule.json"
```
Used Quark Script APIs/Tools that LLM used:  `Rule()`

```
2nd Prompt: Run Quark Analysis using the rule instance on the apk sample "ovaa.apk", 
            and Check if the parameters are hard-coded. If yes, display the hard-coded values.
```
Used Quark Script APIs/Tools that LLM used: `runQuarkAnalysis()`, `getParameterValues()` and `isHardCoded()`


### Architecture
The `Rule()`, `runQuarkAnalysis()`, `getParameterValues()`, and `isHardCoded()` functions are treated as **tools** within LangChain, enabling them to be invoked through the `gpt-4o` model to analyze and identify [CWE-798](https://cwe.mitre.org/data/definitions/798.html) vulnerabilities in the [ovaa.apk](https://github.com/oversecured/ovaa) sample.

<img width="829" alt="截圖 2024-07-26 下午3 40 32" src="https://github.com/user-attachments/assets/f17bfba0-43d7-4236-9775-bb0d3b961907">


* Notes: 
  1. Since LangChain currently does not support passing Python instances between tools, we are temporarily using global variables to pass parameters between tools in `quarkScriptAgent.py`.
  2. This is a POC (Prove of Concept) the paths of the apk file and the rule file are hard-coded in the quarkScriptAgent.py
  3. A web GUI is under construction, please stay tuned!

2024-07-26 14:21 UTC, haeter525 commented on quarkScriptAgent.py
> +    """
This tool only loads the rule from a given path. We could keep its name and its docstring simple. For example,

```python
@tool
def loadRule(rule_path: str):
    """
    Given a rule path,
    this instance loads a rule from the rule path.
    """
    ...
```

2024-07-26 14:54 UTC, haeter525 requested changes

2024-07-26 14:54 UTC, haeter525 commented on quarkScriptAgent.py
> +    this instance runs the basic Quark.
I suggest replacing `the basic Quark` with `the Quark analysis` to make the docstring consistent with the tool's name.

2024-07-26 14:54 UTC, haeter525 commented on quarkScriptAgent.py
> +def getBehaviorOccurLise():
There is a typo, `Lise`.

2024-07-26 14:54 UTC, haeter525 commented on quarkScriptAgent.py
> +    # check parameters values are hard-coded
There is also a typo, `parameter values`.

2024-07-26 14:54 UTC, haeter525 commented on quarkScriptAgent.py
I recommend formatting the code with `black` to provide a consistent coding style.

2024-07-27 04:16 UTC, haeter525 requested changes

2024-07-27 04:16 UTC, haeter525 commented on quarkScriptAgent.py
> +    defineRuleByJson,
This should be `loadRule`.

2024-07-27 04:16 UTC, haeter525 commented on quarkScriptAgent.py
> +    getBehaviorOccurLise,
This should be `getBehaviorOccurList`.

2024-07-27 04:16 UTC, haeter525 commented on quarkScriptAgent.py
> +def loadRule(rulePath):
Please add a type hint for `rulePath`.
```python
def loadRule(rulePath: str):
```


Without the type hint, the LLM can not pass the rule path to this tool. Here is the error output.

```
User Input: Initialize the rule instance with the rule path set to "rule.json"

Agent:  The rule has been successfully initialized with the path set to "rule.json". What would you like to do next?

User Input: Run Quark Analysis using the rule instance on the apk sample "ovaa.apk",             and Check if the parameters are hard-coded. If yes, display the hard-coded values.
Traceback (most recent call last):
  File "/Users/shengfeng/codespace/quark-script/quarkScriptAgent.py", line 137, in <module>
    response = agent_executor.invoke({
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain/chains/base.py", line 166, in invoke
    raise e
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 1612, in _call
    next_step_output = self._take_next_step(
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 1318, in _take_next_step
    [
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 1318, in <listcomp>
    [
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 1403, in _iter_next_step
    yield self._perform_agent_action(
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 1425, in _perform_agent_action
    observation = tool.run(
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain_core/tools.py", line 634, in run
    raise error_to_raise
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain_core/tools.py", line 607, in run
    response = context.run(self._run, *tool_args, **tool_kwargs)
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/langchain_core/tools.py", line 944, in _run
    return self.func(*args, **kwargs)
  File "/Users/shengfeng/codespace/quark-script/quarkScriptAgent.py", line 29, in loadRule
    ruleInstance = Rule(rulePath)
  File "/Users/shengfeng/codespace/quark-script/.venv/lib/python3.9/site-packages/quark/core/struct/ruleobject.py", line 38, in __init__
    with open(ruleJson) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/rule'
```

2024-07-27 06:03 UTC, haeter525 approved these changes
LGTM. Thank @pulorsok !

2024-07-27 06:05 UTC, merged